runlist:
  "2016_preVFP":
    [
      "Run2016_preVFB_B",
      "Run2016_preVFB_C",
      "Run2016_preVFB_D",
      "Run2016_preVFB_E",
      "Run2016_preVFB_F",
    ]
  "2016_postVFP": ["2016_postVFP_F", "2016_postVFP_G", "2016_postVFP_H"]
  "2017": ["Run2017B", "Run2017C", "Run2017D", "Run2017E", "Run2017F"]
  "2018": ["Run2018A", "Run2018B", "Run2018C", "Run2018D"]
generator_cuts:
  "2016_preVFP":
    "MuTau":
      "lep1_pt":
      "lep1_eta":
      "lep2_pt":
      "lep2_eta":
      "attempts": 1000
    "ElTau":
      "lep1_pt":
      "lep1_eta":
      "lep2_pt":
      "lep2_eta":
      "attempts": 1000
    "ElMu":
      "lep1_pt":
      "lep1_eta":
      "lep2_pt":
      "lep2_eta":
      "attempts": 1000
    "TauTau":
      "lep1_pt":
      "lep1_eta":
      "lep2_pt":
      "lep2_eta":
      "attempts": 1000
    "MuEmb":
      "lep1_pt":
      "lep1_eta":
      "lep2_pt":
      "lep2_eta":
      "attempts": 1
    "ElEmb":
      "lep1_pt":
      "lep1_eta":
      "lep2_pt":
      "lep2_eta":
      "attempts": 1
  "2016_postVFP":
    "MuTau":
      "lep1_pt":
      "lep1_eta":
      "lep2_pt":
      "lep2_eta":
      "attempts": 1000
    "ElTau":
      "lep1_pt":
      "lep1_eta":
      "lep2_pt":
      "lep2_eta":
      "attempts": 1000
    "ElMu":
      "lep1_pt":
      "lep1_eta":
      "lep2_pt":
      "lep2_eta":
      "attempts": 1000
    "TauTau":
      "lep1_pt":
      "lep1_eta":
      "lep2_pt":
      "lep2_eta":
      "attempts": 1000
    "MuEmb":
      "lep1_pt":
      "lep1_eta":
      "lep2_pt":
      "lep2_eta":
      "attempts": 1
    "ElEmb":
      "lep1_pt":
      "lep1_eta":
      "lep2_pt":
      "lep2_eta":
      "attempts": 1
  "2017":
    "MuTau":
      "lep1_pt": 18
      "lep1_eta": 2.2
      "lep2_pt": 18
      "lep2_eta": 2.4
      "attempts": 1000
    "ElTau":
      "lep1_pt": 18
      "lep1_eta": 2.2
      "lep2_pt": 18
      "lep2_eta": 2.4
      "attempts": 1000
    "ElMu":
      "lep1_pt": 9
      "lep1_eta": 2.5
      "lep2_pt": 19
      "lep2_eta": 2.5
      "attempts": 1000
    "TauTau":
      "lep1_pt": 20
      "lep1_eta": 2.2
      "lep2_pt": 20
      "lep2_eta": 2.2
      "attempts": 1000
    "MuEmb":
      "lep1_pt": 17
      "lep1_eta": 2.5
      "lep2_pt": 8
      "lep2_eta": 2.5
      "attempts": 1
    "ElEmb":
      "lep1_pt": 22
      "lep1_eta": 2.5
      "lep2_pt": 10
      "lep2_eta": 2.5
      "attempts": 1
  "2018":
    "MuTau":
      "lep1_pt": 18
      "lep1_eta": 2.2
      "lep2_pt": 18
      "lep2_eta": 2.4
      "attempts": 1000
    "ElTau":
      "lep1_pt": 18
      "lep1_eta": 2.2
      "lep2_pt": 18
      "lep2_eta": 2.4
      "attempts": 1000
    "ElMu":
      "lep1_pt": 9
      "lep1_eta": 2.5
      "lep2_pt": 19
      "lep2_eta": 2.5
      "attempts": 1000
    "TauTau":
      "lep1_pt": 20
      "lep1_eta": 2.2
      "lep2_pt": 20
      "lep2_eta": 2.2
      "attempts": 1000
    "MuEmb":
      "lep1_pt": 17
      "lep1_eta": 2.5
      "lep2_pt": 8
      "lep2_eta": 2.5
      "attempts": 1
    "ElEmb":
      "lep1_pt": 22
      "lep1_eta": 2.5
      "lep2_pt": 10
      "lep2_eta": 2.5
      "attempts": 1
finalstate_map:
  "MuTau":
    "name": "MuHad"
    "embeddedParticle": "TauEmbedding"
    "lep1_name": "Mu"
    "lep2_name": "Had"
  "ElTau":
    "name": "ElHad"
    "embeddedParticle": "TauEmbedding"
    "lep1_name": "El"
    "lep2_name": "Had"
  "ElMu":
    "name": "ElMu"
    "embeddedParticle": "TauEmbedding"
    "lep1_name": "El"
    "lep2_name": "Mu"
  "TauTau":
    "name": "HadHad"
    "embeddedParticle": "TauEmbedding"
    "lep1_name": "Had1"
    "lep2_name": "Had2"
  "MuEmb":
    "name": "MuMu"
    "embeddedParticle": "MuEmbedding"
    "lep1_name": "Mu1"
    "lep2_name": "Mu2"
  "ElEmb":
    "name": "ElEl"
    "embeddedParticle": "ElEmbedding"
    "lep1_name": "El1"
    "lep2_name": "El2"
cmssw_version:
  "2016_preVFP":
    "main": "CMSSW_10_6_28"
    "hlt":
  "2016_postVFP":
    "main": "CMSSW_10_6_28"
    "hlt":
  "2017":
    "main": "CMSSW_10_6_28"
    "hlt": "CMSSW_9_4_14_UL_patch1"
  "2018":
    "main": "CMSSW_10_6_28"
    "hlt": "CMSSW_10_2_16_UL"
output_paths:
  "tarballs": "srm://cmssrm-kit.gridka.de:8443/srm/managerv2?SFN=/pnfs/gridka.de/cms/disk-only/store/user/{USER}/ul_embedding/tarballs_dez20"
  "preselection": "srm://cmssrm-kit.gridka.de:8443/srm/managerv2?SFN=/pnfs/gridka.de/cms/disk-only/store/user/{USER}/ul_embedding/preselection"
  "main": "srm://cmssrm-kit.gridka.de:8443/srm/managerv2?SFN=/pnfs/gridka.de/cms/disk-only/store/user/{USER}/ul_embedding/miniaod"
  "nanoaod": "srm://cmssrm-kit.gridka.de:8443/srm/managerv2?SFN=/pnfs/gridka.de/cms/disk-only/store/user/{USER}/ul_embedding/nanoaod"
