runlist: # contains the lists of all runs of the specific eras
  "2016-HIPM": # pre VFP version
    [
      "Run2016-HIPM_B_ver1",
      "Run2016-HIPM_B_ver2",
      "Run2016-HIPM_C",
      "Run2016-HIPM_D",
      "Run2016-HIPM_E",
      "Run2016-HIPM_F",
    ]
  "2016": ["Run2016_F", "Run2016_G", "Run2016_H"]
  "2017": ["Run2017B", "Run2017C", "Run2017D", "Run2017E", "Run2017F"]
  "2018": ["Run2018A", "Run2018B", "Run2018C", "Run2018D"]
input_samples:
  "2016-HIPM": # pre VFP version
    "Run2016-HIPM_B_ver1": "/DoubleMuon/Run2016B-v1/RAW"
    "Run2016-HIPM_B_ver2": "/DoubleMuon/Run2016B-v2/RAW"
    "Run2016-HIPM_C": "/DoubleMuon/Run2016C-v2/RAW"
    "Run2016-HIPM_D": "/DoubleMuon/Run2016D-v2/RAW"
    "Run2016-HIPM_E": "/DoubleMuon/Run2016E-v2/RAW"
    "Run2016-HIPM_F": "/DoubleMuon/Run2016F-v1/RAW"
  "2016":
    "Run2016_F": "/DoubleMuon/Run2016F-v1/RAW"
    "Run2016_G": "/DoubleMuon/Run2016G-v1/RAW"
    "Run2016_H": "/DoubleMuon/Run2016H-v1/RAW"
  "2017":
    "Run2017B": "/DoubleMuon/Run2017B-v1/RAW"
    "Run2017C": "/DoubleMuon/Run2017C-v1/RAW"
    "Run2017D": "/DoubleMuon/Run2017D-v1/RAW"
    "Run2017E": "/DoubleMuon/Run2017E-v1/RAW"
    "Run2017F": "/DoubleMuon/Run2017F-v1/RAW"
  "2018":
    "Run2018A": "/DoubleMuon/Run2018A-v1/RAW"
    "Run2018B": "/DoubleMuon/Run2018B-v1/RAW"
    "Run2018C": "/DoubleMuon/Run2018C-v1/RAW"
    "Run2018D": "/DoubleMuon/Run2018D-v1/RAW"
globaltag_names:
  "2016-HIPM": "inputDoubleMu_106X_ULegacy_miniAOD-v1"
  "2016": "inputDoubleMu_106X_ULegacy_miniAOD-v1"
  "2017": "inputDoubleMu_106X_ULegacy_miniAOD-v1"
  "2018": "inputDoubleMu_106X_ULegacy_miniAOD-v1"
generator_cuts:
  "2016-HIPM":
    "MuTau":
      "lep1_pt": 18
      "lep1_eta": 2.2
      "lep2_pt": 18
      "lep2_eta": 2.4
      "attempts": 1000
    "ElTau":
      "lep1_pt": 18
      "lep1_eta": 2.2
      "lep2_pt": 18
      "lep2_eta": 2.4
      "attempts": 1000
    "ElMu":
      "lep1_pt": 9
      "lep1_eta": 2.5
      "lep2_pt": 19
      "lep2_eta": 2.5
      "attempts": 1000
    "TauTau":
      "lep1_pt": 20
      "lep1_eta": 2.2
      "lep2_pt": 20
      "lep2_eta": 2.2
      "attempts": 1000
    "MuEmb":
      "lep1_pt": 17
      "lep1_eta": 2.5
      "lep2_pt": 8
      "lep2_eta": 2.5
      "attempts": 1
    "ElEmb":
      "lep1_pt": 22
      "lep1_eta": 2.5
      "lep2_pt": 10
      "lep2_eta": 2.5
      "attempts": 1
  "2016":
    "MuTau":
      "lep1_pt": 18
      "lep1_eta": 2.2
      "lep2_pt": 18
      "lep2_eta": 2.4
      "attempts": 1000
    "ElTau":
      "lep1_pt": 18
      "lep1_eta": 2.2
      "lep2_pt": 18
      "lep2_eta": 2.4
      "attempts": 1000
    "ElMu":
      "lep1_pt": 9
      "lep1_eta": 2.5
      "lep2_pt": 19
      "lep2_eta": 2.5
      "attempts": 1000
    "TauTau":
      "lep1_pt": 20
      "lep1_eta": 2.2
      "lep2_pt": 20
      "lep2_eta": 2.2
      "attempts": 1000
    "MuEmb":
      "lep1_pt": 17
      "lep1_eta": 2.5
      "lep2_pt": 8
      "lep2_eta": 2.5
      "attempts": 1
    "ElEmb":
      "lep1_pt": 22
      "lep1_eta": 2.5
      "lep2_pt": 10
      "lep2_eta": 2.5
      "attempts": 1
  "2017":
    "MuTau":
      "lep1_pt": 18
      "lep1_eta": 2.2
      "lep2_pt": 18
      "lep2_eta": 2.4
      "attempts": 1000
    "ElTau":
      "lep1_pt": 18
      "lep1_eta": 2.2
      "lep2_pt": 18
      "lep2_eta": 2.4
      "attempts": 1000
    "ElMu":
      "lep1_pt": 9
      "lep1_eta": 2.5
      "lep2_pt": 19
      "lep2_eta": 2.5
      "attempts": 1000
    "TauTau":
      "lep1_pt": 20
      "lep1_eta": 2.2
      "lep2_pt": 20
      "lep2_eta": 2.2
      "attempts": 1000
    "MuEmb":
      "lep1_pt": 17
      "lep1_eta": 2.5
      "lep2_pt": 8
      "lep2_eta": 2.5
      "attempts": 1
    "ElEmb":
      "lep1_pt": 22
      "lep1_eta": 2.5
      "lep2_pt": 10
      "lep2_eta": 2.5
      "attempts": 1
  "2018":
    "MuTau":
      "lep1_pt": 18
      "lep1_eta": 2.2
      "lep2_pt": 18
      "lep2_eta": 2.4
      "attempts": 1000
    "ElTau":
      "lep1_pt": 18
      "lep1_eta": 2.2
      "lep2_pt": 18
      "lep2_eta": 2.4
      "attempts": 1000
    "ElMu":
      "lep1_pt": 9
      "lep1_eta": 2.5
      "lep2_pt": 19
      "lep2_eta": 2.5
      "attempts": 1000
    "TauTau":
      "lep1_pt": 20
      "lep1_eta": 2.2
      "lep2_pt": 20
      "lep2_eta": 2.2
      "attempts": 1000
    "MuEmb":
      "lep1_pt": 17
      "lep1_eta": 2.5
      "lep2_pt": 8
      "lep2_eta": 2.5
      "attempts": 1
    "ElEmb":
      "lep1_pt": 22
      "lep1_eta": 2.5
      "lep2_pt": 10
      "lep2_eta": 2.5
      "attempts": 1
finalstate_map:
  "MuTau":
    "name": "MuHad"
    "embeddedParticle": "TauEmbedding"
    "lep1_name": "Mu"
    "lep2_name": "Had"
    "FullName": "MuTauFinalState"
  "ElTau":
    "name": "ElHad"
    "embeddedParticle": "TauEmbedding"
    "lep1_name": "El"
    "lep2_name": "Had"
    "FullName": "ElTauFinalState"
  "ElMu":
    "name": "ElMu"
    "embeddedParticle": "TauEmbedding"
    "lep1_name": "El"
    "lep2_name": "Mu"
    "FullName": "ElMuFinalState"
  "TauTau":
    "name": "HadHad"
    "embeddedParticle": "TauEmbedding"
    "lep1_name": "Had1"
    "lep2_name": "Had2"
    "FullName": "TauTauFinalState"
  "MuEmb":
    "name": "MuMu"
    "embeddedParticle": "MuEmbedding"
    "lep1_name": "Mu1"
    "lep2_name": "Mu2"
    "FullName": "MuonEmbedding"
  "ElEmb":
    "name": "ElEl"
    "embeddedParticle": "ElEmbedding"
    "lep1_name": "El1"
    "lep2_name": "El2"
    "FullName": "ElectronEmbedding"
cmssw_version:
  "2016-HIPM":
    "main": "CMSSW_10_6_28"
    "hlt": "CMSSW_8_0_33_UL"
  "2016":
    "main": "CMSSW_10_6_28"
    "hlt": "CMSSW_8_0_33_UL"
  "2017":
    "main": "CMSSW_10_6_28"
    "hlt": "CMSSW_9_4_14_UL_patch1"
  "2018":
    "main": "CMSSW_10_6_28"
    "hlt": "CMSSW_10_2_16_UL"
output_paths:
               srm://cmssrm-kit.gridka.de:8443/srm/managerv2?SFN=/pnfs/gridka.de/cms/disk-only/store/user/cwinter/ul_embedding_better_cleaning/
  "tarballs": "srm://cmssrm-kit.gridka.de:8443/srm/managerv2?SFN=/pnfs/gridka.de/cms/disk-only/store/user/{USER}/ul_embedding/tarballs_dez2022"
  "preselection": "srm://cmssrm-kit.gridka.de:8443/srm/managerv2?SFN=/pnfs/gridka.de/cms/disk-only/store/user/{USER}/ul_embedding/preselection"
  "main": "srm://cmssrm-kit.gridka.de:8443/srm/managerv2?SFN=/pnfs/gridka.de/cms/disk-only/store/user/{USER}/ul_embedding/miniaod"
  "large_miniAOD": "srm://cmssrm-kit.gridka.de:8443/srm/managerv2?SFN=/pnfs/gridka.de/cms/disk-only/store/user/{USER}/ul_embedding/large_miniAOD"
  "rerun_puppi": "srm://cmssrm-kit.gridka.de:8443/srm/managerv2?SFN=/pnfs/gridka.de/cms/disk-only/store/user/{USER}/ul_embedding/large_miniAOD_v2"
  "nanoaod": "srm://cmssrm-kit.gridka.de:8443/srm/managerv2?SFN=/pnfs/gridka.de/cms/disk-only/store/user/{USER}/ul_embedding_nanoaod/v3"

tmux_path: "/home/cwinter/.apps/CentOSLinux7/bin/tmux"
